ALTER TABLE `proxy_stats_snapshots`
  MODIFY COLUMN `today_request` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `today_success` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `today_cost` DECIMAL(16, 4) NOT NULL DEFAULT 0.0000,
  MODIFY COLUMN `week_request` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `week_success` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `week_cost` DECIMAL(16, 4) NOT NULL DEFAULT 0.0000,
  MODIFY COLUMN `month_request` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `month_success` BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN `month_cost` DECIMAL(16, 4) NOT NULL DEFAULT 0.0000,
  MODIFY COLUMN `months_request` LONGTEXT NULL,
  MODIFY COLUMN `months_success` LONGTEXT NULL,
  MODIFY COLUMN `months_cost` LONGTEXT NULL;
